#server:
#  port: 9088
#
#
#
#spring:
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/dbippp
#    username: postgres
#    password: passer
#    driver-class-name: org.postgresql.Driver
#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/auth-realm
#
#          jwk-set-uri: http://localhost:8080/realms/auth-realm/protocol/openid-connect/certs
#